package sirs.remotedocs.demos;


import sirs.remotedocs.Library;
import types.Buffer_t;
import utils.CryptoUtils;

import java.util.logging.Level;
import java.util.logging.Logger;

import static javax.xml.bind.DatatypeConverter.printHexBinary;

/*  Demo Class used for demonstrating a client connecting to the File Server, 
    and issuing a write command on a file that does not belong to him.
    This aims to simulate an attacker that "steals" another user's ID.

    Please refer to the output generated by the server at runtime as it
    receives and processes the Demo Apps requests, for information on the 
    exceptions caught by the file system, and the returns of the operations 
    being performed by the server.
 */
public class DemoWriteToAnotherClientsFile {

    public static void main(String[] args) {
        try {
            Library c1 = new Library();
            Library c2 = new Library();
            Buffer_t buffer = new Buffer_t(CryptoUtils.serialize(""));
            
            // Initializing the file system
            System.out.println("CLIENT 1");
            System.out.println("Initializing the File System...");
            c1.fs_init();
            System.out.println("Done!");
            System.out.println("Client ID assigned by server: " + c1.getClientID().getValue());
            System.out.println("---------------------------------------------------------\n");

            // Initializing the file system
            System.out.println("CLIENT 2");
            System.out.println("Initializing the File System...");
            c2.fs_init();
            System.out.println("Done!");
            System.out.println("Client ID assigned by server: " + c2.getClientID().getValue());
            System.out.println("---------------------------------------------------------\n");
            
            final String s = "The quick brown fox jumps over the lazy dog";
            buffer.setValue(CryptoUtils.serialize(s));
            // Writing to client 1's file, at position 0.
            System.out.println("CLIENT 1");
            System.out.println("Writing some data of size " + buffer.getValue().length + "to client 1's file, at pos 0 ...");
            c1.fs_write(0, buffer.getValue().length, buffer);
            System.out.println("Done!");
            System.out.println("Data sent to the file system:  " + printHexBinary(buffer.getValue()));
            System.out.println("---------------------------------------------------------\n");
            
            //Stealing client 1's ID
            c2.setClientID(c1.getClientID());
            
            // Writing to client 1's file, as client 2.
            System.out.println("CLIENT 2");
            System.out.println("Writing some data of size " + buffer.getValue().length + " to client 1's file, as client 2 ...");
            c2.fs_write(0, buffer.getValue().length, buffer);       
            
        } catch (Exception ex) {
            Logger.getLogger(DemoReadFileByID.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
