package sirs.remotedocs.demos;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import sirs.remotedocs.Library;
import types.Id_t;

/*  Demo Class used for demonstrating a client connecting to the File Server, 
    and issuing a list command for the Public Key list.

    Please refer to the output generated by the server at runtime as it
    receives and processes the Demo Apps requests, for information on the 
    exceptions caught by the file system, and the returns of the operations 
    being performed by the server.
 */
public class DemoFetchPKeyList {

    public static void main(String[] args) {
        try {
            Library c = new Library();
            
            // Initializing the file system
            System.out.println("Initializing the File System...");
            c.fs_init();
            System.out.println("Done!");
            System.out.println("Client ID assigned by server: " + c.getClientID().getValue());
            System.out.println("---------------------------------------------------------\n");
            
            // Reading the List of Public Keys
            System.out.println("Reading the Public Key list...");
            @SuppressWarnings("unchecked") List<Id_t> pKeyList = c.fs_list();
            System.out.println("Done!");
            System.out.println("PKey List:");
            for (int i = 0; i < pKeyList.size(); i++) {
                System.out.println("   " + pKeyList.get(i).getValue());
            }
            System.out.println("---------------------------------------------------------\n");                
            
        } catch (Exception ex) {
            Logger.getLogger(DemoFetchPKeyList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
